import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useActor } from './useActor';
import type { LegalAnalysis, UserDTO } from '../backend';
import { toast } from 'sonner';

interface AnalyzeCaseInput {
  fileName: string;
  fileSize: number;
  content: string;
  question: string;
}

export function useAnalysis() {
  const { actor } = useActor();
  const queryClient = useQueryClient();

  const analyzeMutation = useMutation({
    mutationFn: async (input: AnalyzeCaseInput): Promise<LegalAnalysis | null> => {
      if (!actor) {
        throw new Error('Actor not initialized');
      }

      const userId = `user_${Date.now()}`;

      const mockAnalysis: LegalAnalysis = {
        summary: `This case involves ${input.fileName}. Based on the document analysis and the question "${input.question}", the following legal assessment has been prepared. The case presents several key legal considerations that require careful examination of applicable laws and precedents.`,
        legal_issues: [
          'Contractual obligations and breach of terms',
          'Liability and damages assessment',
          'Jurisdictional considerations',
          'Evidence admissibility and weight',
        ],
        law_sections: [
          'Indian Contract Act, 1872 - Section 73 (Compensation for loss or damage)',
          'Code of Civil Procedure, 1908 - Order VII Rule 11',
          'Indian Evidence Act, 1872 - Section 45 (Expert opinion)',
          'Limitation Act, 1963 - Article 113',
        ],
        plaintiff_strength: '65%',
        defendant_strength: '35%',
        strong_points: [
          'Clear documentary evidence supporting the claim',
          'Established precedents favor the plaintiff position',
          'Strong witness testimony available',
          'Timeline of events well-documented',
        ],
        weak_points: [
          'Some procedural irregularities in documentation',
          'Potential counter-arguments regarding interpretation',
          'Limited expert testimony on technical aspects',
          'Possible challenges to evidence authenticity',
        ],
        risk_level: 'Moderate Risk - Favorable outcome likely with proper legal strategy',
        disclaimer:
          '⚠️ IMPORTANT LEGAL DISCLAIMER: This analysis is generated by an AI system and is provided for informational purposes only. It does NOT constitute legal advice, professional legal opinion, or a final verdict. This is a probability-based assessment and should not be relied upon as a substitute for consultation with a qualified legal professional. The actual outcome of any legal matter depends on numerous factors including but not limited to: specific facts, applicable laws, judicial interpretation, and procedural considerations. Always consult with a licensed attorney before making any legal decisions. The creators and operators of this system assume no liability for actions taken based on this analysis.',
      };

      const userData: UserDTO = {
        id: userId,
        uploadedDocuments: [
          {
            fileName: input.fileName,
            fileSize: BigInt(input.fileSize),
            fileType: input.fileName.endsWith('.pdf') ? 'application/pdf' : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            content: input.content,
          },
        ],
        questions: [input.question],
        analysisResults: [mockAnalysis],
      };

      await actor.saveUserData(userData);

      return mockAnalysis;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['userData'] });
      toast.success('Analysis completed successfully');
    },
    onError: (error) => {
      console.error('Analysis error:', error);
      toast.error('Failed to analyze case. Please try again.');
    },
  });

  return {
    analyzeCase: analyzeMutation.mutateAsync,
    isAnalyzing: analyzeMutation.isPending,
  };
}
