/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DocumentData = IDL.Record({
  'content' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
});
export const LegalAnalysis = IDL.Record({
  'defendant_strength' : IDL.Text,
  'summary' : IDL.Text,
  'risk_level' : IDL.Text,
  'disclaimer' : IDL.Text,
  'plaintiff_strength' : IDL.Text,
  'legal_issues' : IDL.Vec(IDL.Text),
  'strong_points' : IDL.Vec(IDL.Text),
  'law_sections' : IDL.Vec(IDL.Text),
  'weak_points' : IDL.Vec(IDL.Text),
});
export const UserDTO = IDL.Record({
  'id' : IDL.Text,
  'uploadedDocuments' : IDL.Vec(DocumentData),
  'questions' : IDL.Vec(IDL.Text),
  'analysisResults' : IDL.Vec(LegalAnalysis),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'deleteUserData' : IDL.Func([IDL.Text], [], []),
  'getAllUserData' : IDL.Func([], [IDL.Vec(UserDTO)], ['query']),
  'getUserData' : IDL.Func([IDL.Text], [IDL.Opt(UserDTO)], ['query']),
  'saveUserData' : IDL.Func([UserDTO], [UserDTO], []),
  'updateUserData' : IDL.Func([IDL.Text, UserDTO], [UserDTO], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DocumentData = IDL.Record({
    'content' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
  });
  const LegalAnalysis = IDL.Record({
    'defendant_strength' : IDL.Text,
    'summary' : IDL.Text,
    'risk_level' : IDL.Text,
    'disclaimer' : IDL.Text,
    'plaintiff_strength' : IDL.Text,
    'legal_issues' : IDL.Vec(IDL.Text),
    'strong_points' : IDL.Vec(IDL.Text),
    'law_sections' : IDL.Vec(IDL.Text),
    'weak_points' : IDL.Vec(IDL.Text),
  });
  const UserDTO = IDL.Record({
    'id' : IDL.Text,
    'uploadedDocuments' : IDL.Vec(DocumentData),
    'questions' : IDL.Vec(IDL.Text),
    'analysisResults' : IDL.Vec(LegalAnalysis),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'deleteUserData' : IDL.Func([IDL.Text], [], []),
    'getAllUserData' : IDL.Func([], [IDL.Vec(UserDTO)], ['query']),
    'getUserData' : IDL.Func([IDL.Text], [IDL.Opt(UserDTO)], ['query']),
    'saveUserData' : IDL.Func([UserDTO], [UserDTO], []),
    'updateUserData' : IDL.Func([IDL.Text, UserDTO], [UserDTO], []),
  });
};

export const init = ({ IDL }) => { return []; };