/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DocumentData {
  'content' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'fileType' : string,
}
export interface LegalAnalysis {
  'defendant_strength' : string,
  'summary' : string,
  'risk_level' : string,
  'disclaimer' : string,
  'plaintiff_strength' : string,
  'legal_issues' : Array<string>,
  'strong_points' : Array<string>,
  'law_sections' : Array<string>,
  'weak_points' : Array<string>,
}
export interface UserDTO {
  'id' : string,
  'uploadedDocuments' : Array<DocumentData>,
  'questions' : Array<string>,
  'analysisResults' : Array<LegalAnalysis>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'deleteUserData' : ActorMethod<[string], undefined>,
  'getAllUserData' : ActorMethod<[], Array<UserDTO>>,
  'getUserData' : ActorMethod<[string], [] | [UserDTO]>,
  'saveUserData' : ActorMethod<[UserDTO], UserDTO>,
  'updateUserData' : ActorMethod<[string, UserDTO], UserDTO>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];